<h2 style="text-align: center">Moje výpůjčky</h2>

<table id="tab_vypujcky">
    <thead>
        <tr>
            <th>Kniha</th>
            <th>Od</th>
            <th>Do</th>
            <th>Zbývá dnů</th>
        </tr>
    </thead>
    <tbody>
    <?php
        $user = Mage::getModel('core/session')->getLoggedUser();
        $vypujcky = $this->getCtenarVypujcky($user->getId());
        $date1 = new DateTime(date("y-m-d"));

            foreach($vypujcky as $vypujcka) {
                    echo '<tr>';
                        $book_name = Mage::getModel('tituly/tituly')->load($vypujcka->getBook())->getNazev();
                        echo '<td>'.$book_name.'</td>';
                        echo '<td>'.$vypujcka->getFrom().'</td>';
                        echo '<td>'.$vypujcka->getTo().'</td>';
                        $date2 = new DateTime($vypujcka->getTo());
                        $interval = $date1->diff($date2,false);
                        $days_Left = $interval->format('%R%d');
                        //echo $interval->format('%R%d');
                        if ($date1 >= $date2) {
                            echo '<td style="color: red">'.$days_Left.'</td>';
                        }
                        else {
                            echo '<td style="color: green">'.$days_Left.'</td>';
                        }

                    echo '</tr>';
            }
    ?>
    </tbody>
</table>