<h3>Výpůjčky čtenáře</h3>
    <table>
        <thead>
            <tr><th>Kniha</th><th>Od</th><th>Do</th></tr>
        </thead>
        <tbody>
<?php
    $user = Mage::getModel('core/session')->getLoggedUser();
    $vypujcky = $this->getCtenarVypujcky($user->getId());
        foreach($vypujcky as $vypujcka) {
            ?>
            <tr>
                <?php
                    $book_name = Mage::getModel('tituly/tituly')->getName($vypujcka->getBook());
                    echo '<td>'.$book_name.'</td>';
                    echo '<td>'.$vypujcka->getFrom().'</td>';
                    echo '<td>'.$vypujcka->getTo().'</td>';
                ?>
            </tr>
<?php
        }
?>
        </tbody>
    </table>
