<?php
/**
 * Created by JetBrains PhpStorm.
 * User: tichave4
 * Date: 14.2.13
 * Time: 15:16
 * To change this template use File | Settings | File Templates.
 */
?>
<?php
/** @var $ctenar Knihovna_Ctenar_Model_Ctenar */
$ctenar= $this->getCtenar();
?>
<div id="info" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<h3>Info o ctenari</h3>
    <b>Číslo průkazu:</b> <?php echo $ctenar->getCisloprukazky();?><br>
    <b>Jméno:</b> <?php echo $ctenar->getJmeno();?><br>
    <b>Příjmení:</b> <?php echo $ctenar->getPrijmeni();?><br>
    <b>Ulice:</b> <?php echo $ctenar->getUlice();?><br>
    <b>Číslo popisné:</b> <?php echo $ctenar->getCp();?><br>
    <b>Město:</b> <?php echo $ctenar->getMesto();?><br>
    <b>PSČ:</b> <?php echo $ctenar->getPsc();?><br>
    <b>Email:</b> <?php echo $ctenar->getEmail();?><br>
    <b>Telefonní číslo:</b> <?php echo $ctenar->getTelefonni_cislo();?><br>


</div>


