<?php
/**
 * Created by JetBrains PhpStorm.
 * User: tichave4
 * Date: 14.2.13
 * Time: 15:16
 * To change this template use File | Settings | File Templates.
 */
?>
<?php
/** @var $ctenar Knihovna_Ctenar_Model_Ctenar */
$ctenar= $this->getCtenar();
?>
<div id="info" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<h3>Info o ctenari</h3>
    <b>Číslo průkazu:</b> <?php echo $ctenar->getCislo_prukazu();?><br>
    <b>Jméno:</b> <?php echo $ctenar->getJmeno();?><br>
    <b>Příjmení:</b> <?php echo $ctenar->getPrijmeni();?><br>
    <b>Ulice:</b> <?php echo $ctenar->getUlice();?><br>
    <b>Číslo popisné:</b> <?php echo $ctenar->getCp();?><br>
    <b>Město:</b> <?php echo $ctenar->getMesto();?><br>
    <b>PSČ:</b> <?php echo $ctenar->getPsc();?><br>
    <b>Email:</b> <?php echo $ctenar->getEmail();?><br>
    <b>Telefonní číslo:</b> <?php echo $ctenar->getTelefonni_cislo();?><br>
    <form id="zmenaHesla" name="zmenaHesla" method="post">
        <label for="password">Nové heslo:</label><input id="password" type="password" name="password"
                                                   class="required-entry input-text">
        <label for="password2">Ověření nového hesla:</label><input id="password2" type="password" name="password"
                                                        class="required-entry input-text">
        <input type="submit" value="Změna hesla">

    </form>
    <script type="text/javascript">
        var loginForm = new VarienForm('zmenaHesla');
    </script>



</div>


