<form id="prihlaseni" name="prihlaseni" method="post">
    <label for="name">Číslo průkazu:</label><input id="name" type="text" name="name" class="required-entry input-text">
    <label for="password3">Heslo:</label><input id="password3" type="password3" name="password"
                                               class="required-entry input-text">
    <input type="submit" value="Přihlásit">

</form>
<script type="text/javascript">
    var loginForm = new VarienForm('prihlaseni');
</script>