<h2 style="text-align: center">Přihlášení čtenáře</h2>
<br>
<hr>
<br>

<form id="prihlaseni" name="prihlaseni" method="post">
    <table id="tab_prihlaseni">
        <tr>
            <td class="td_vnejsi"><label for="name">Číslo průkazu:</label></td>
            <td><input id="name" type="text" name="name" class="required-entry input-text"></td>
        </tr>
        <tr>
            <td class="td_vnejsi"><label for="password">Heslo:</label></td>
            <td><input id="password" type="password" name="password" class="required-entry input-text"></td>
        </tr>
        <tr>
            <td colspan="2"><br></td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center"><input type="submit" value="Přihlásit" style="width: 6em;height: 1.8em"></td>
        </tr>
        <tr>
            <td colspan="2"><br></td>
        </tr>
<form id = "vyresetovani_hesla" method="post" action="">
        <tr>
            <td class="td_vnejsi"><label for="emailova_adresa">E-mail:</label></td>
            <?php
            if( isset($_POST["emailova_adresa"]))
            {
                $uzivateluv_email = $_POST["emailova_adresa"];
                $resource = Mage::getSingleton('core/resource');
                $readConnection = $resource->getConnection('core_read');
                $writeConnection = $resource->getConnection('core_write');

                //vygenerujeme nove nahodne heslo:
                $noveHeslo = sha1(time());



                $query = "UPDATE ctenar SET heslo=sha1('$noveHeslo') WHERE `email`='$uzivateluv_email'";
                $writeConnection->query($query);

                //mail('alt.p@seznam.cz', $pokus, $_POST["emailova_adresa"]);

                $sablonaEmailu = Mage::getModel('core/email_template')->loadDefault('custom_email_template1');



                $promenneProSablonu = array();
                $promenneProSablonu['heslo'] = $noveHeslo;

                //echo $promenneProSablonu['heslo'];
                $sablonaEmailu->setSenderName('Administrace');
                $sablonaEmailu->setSenderEmail('mail');

                $sablonaEmailu->setTemplateSubject('Vaše heslo bylo vyresetováno');

                $sablonaEmailu->send($uzivateluv_email,'John Doe', $promenneProSablonu);
            }

            ?>
            <td><input id="emailova_adresa" type="text" name="emailova_adresa" class="required-entry input-text"></td>
        </tr>
        <tr>
            <td colspan="2"><br></td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center"><input type="submit" value="Vyresetovat heslo (zatím nefunguje)" style="width: 21em;height: 1.8em"></td>
        </tr>
    </table>

</form>
<script type="text/javascript">
    var loginForm = new VarienForm('prihlaseni');
</script>
<tr>
