<h2 style="text-align: center">Přihlášení čtenáře</h2>
<br>
<hr>
<br>

<form id="prihlaseni" name="prihlaseni" method="post">
    <table id="tab_prihlaseni">
        <tr>
            <td class="td_vnejsi"><label for="name">Číslo průkazu:</label></td>
            <td><input id="name" type="text" name="name" class="required-entry input-text"></td>
        </tr>
        <tr>
            <td class="td_vnejsi"><label for="password">Heslo:</label></td>
            <td><input id="password" type="password" name="password" class="required-entry input-text"></td>
        </tr>
        <tr>
            <td colspan="2"><br></td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center"><input type="submit" value="Přihlásit" style="width: 6em;height: 1.8em"></td>
        </tr>
        <tr>
            <td colspan="2"><br></td>
        </tr>
<form method="post" action="">
        <tr>
            <td class="td_vnejsi"><label for="emailova_adresa">E-mail:</label></td>
            <?php
            if( isset($_POST["emailova_adresa"]))
            {
                $uzivateluv_email = isset($_POST["emailova_adresa"]);
                $resource = Mage::getSingleton('core/resource');
                $readConnection = $resource->getConnection('core_read');
                $query = "SELECT * FROM vypujcky";
                $results = $readConnection->fetchAll($query);
                ob_start();
                var_dump($results);
                $pokus = ob_get_clean();
                //v $pokus mame uzivatele, ktery chce vyresetovat heslo

                //vygenerujeme nove nahodne heslo:
                $noveHeslo = sha1(time());

                //zjistime, kteremu uzivateli ho musime nastavit:
                echo $pokus;
                die();


                //mail('alt.p@seznam.cz', $pokus, $_POST["emailova_adresa"]);
            }

            ?>
            <td><input id="emailova_adresa" type="text" name="emailova_adresa" class="required-entry input-text"></td>
        </tr>
        <tr>
            <td colspan="2"><br></td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center"><input type="submit" value="Vyresetovat heslo (zatím nefunguje)" style="width: 21em;height: 1.8em"></td>
        </tr>
    </table>

</form>
<script type="text/javascript">
    var loginForm = new VarienForm('prihlaseni');
</script>
<tr>
