<?php
/**
 * Created by JetBrains PhpStorm.
 * User: tichave4
 * Date: 14.2.13
 * Time: 15:13
 * To change this template use File | Settings | File Templates.
 */
?>

<h1>Moje nástěnka</h1>

<div id="nastenka">
    <!-- <?php echo $this->getChildHtml("vypujcky.vypujckyctenar")?>
    <?php echo $this->getChildHtml("ctenar.info")?>
    <?php echo $this->getChildHtml("")?> -->
    <?php echo $this->getChildHtml()?>
</div>
