<h3>Výpis knih</h3>
    <table>
        <thead>
            <tr><th>Název</th><th>Autor</th><th>ISBN</th></tr>
        </thead>
        <tbody>
        <?php
        $knihy = $this->getKnihy();
        foreach($knihy as $kniha) {
            ?>
        <tr>
            <?php
            $author_name = Mage::getModel('autor/autor')->load($kniha->getId())->getJmeno();
            $author_surname = Mage::getModel('autor/autor')->load($kniha->getId())->getPrijmeni();
            echo '<td>'.$kniha->getNazev().'</td>';
            echo '<td>'.$author_name.' '.$author_surname.'</td>';
            echo '<td>'.$kniha->getIsbn().'</td>';
            ?>
        </tr>
            <?php
        }
        ?>
        </tbody>
    </table>
