<h3>Výpis knih</h3>
<input style="text"><input style="button">
    <table id="seznam_knih">
        <thead>
            <tr><th>Název</th><th>Autor</th><th>ISBN</th><th>Počet stránek</th><th>Rok vydání</th></tr>
        </thead>
        <tbody>
        <?php
        $knihy = $this->getKnihy();
        foreach($knihy as $kniha) {
            ?>
        <tr>
            <?php
            $authors = explode(', ',$kniha->getAutor());
            $i = 0;
            $author_name = array();
            foreach($authors as $author) {
                array_push($author_name, Mage::getModel('autor/autor')->load($author)->getJmeno().
                    ' '.Mage::getModel('autor/autor')->load($author)->getPrijmeni());
            }
            $authors = implode(' ,',$author_name);
            echo '<td>'.$kniha->getNazev().'</td>';
            echo '<td>'.$authors.'</td>';
            echo '<td>'.$kniha->getIsbn().'</td>';
            echo '<td>'.$kniha->getPocet_stranek().'</td>';
            echo '<td>'.$kniha->getRok_vydani().'</td>';
            ?>
        </tr>
            <?php
        }
        ?>
        </tbody>
    </table>
