<h3>Výpis knih</h3>
    <table>
        <thead>
            <tr><th>Název</th><th>Autor</th><th>ISBN</th></tr>
        </thead>
        <tbody>
        <?php
        $knihy = $this->getKnihy();
        foreach($knihy as $kniha) {
            ?>
        <tr>
            <?php
            $authors = explode(', ',$kniha->getAutor);
            $i = 0;
            foreach($authors as $author) {
                $author_name[$i] = Mage::getModel('autor/autor')->load($author)->getJmeno().
                    ' '.Mage::getModel('autor/autor')->load($author)->getPrijmeni();
            }
            $authors = implode(' ,',$author_name);
            echo '<td>'.$kniha->getNazev().'</td>';
            echo '<td>'.$authors.'</td>';
            echo '<td>'.$kniha->getIsbn().'</td>';
            ?>
        </tr>
            <?php
        }
        ?>
        </tbody>
    </table>
